[build]
  command = "npm run build"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/roymen/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/roymen/health"
  status = 200
  force = true
